version: "3"

vars:
  WEB_DIR: "./web"
  SECOND_VAR: "{{.FIRST_VAR}} world"

tasks:
  migrate:
    cmds:
      - tern migrate --config third_party/tern/tern.conf --migrations third_party/tern
    silent: true

  buildgo:
    cmds:
      - echo {{.SECOND_VAR}}
      - cd ./cmd/nrtm4client && go build -o nrtm4client -v
      - cd ./cmd/nrtm4serve && go build -o nrtm4serve -v
    silent: true

  testgo:
    cmds:
      - go test ./internal/...
    silent: true

  installweb:
    precondition: test ! -d node_modules
    cmds:
      - cd {{.WEB_DIR}} && npm install --verbose
    silent: true

  buildweb:
    deps: [installweb]
    cmds:
      - cd {{.WEB_DIR}} && npm run build
    silent: true

  testweb:
    deps: [installweb]
    cmds:
      - cd {{.WEB_DIR}} && npx vitest run
    silent: true

  webdev:
    deps: [installweb]
    cmds:
      - cd {{.WEB_DIR}} && npm run dev
    silent: true

  build:
    deps: [buildgo, buildweb]
    silent: true

  test:
    deps: [testgo, testweb]
    silent: true

  install:
    deps: [buildgo, testgo, buildweb, testweb]
    silent: true

  clean:
    cmds:
      - rm -rf ./web/dist ./cmd/nrtmclient/__debug_* ./cmd/nrtmserve/__debug_*
    silent: true

  cleanall:
    deps: [clean]
    cmds:
      - rm -rf {{.WEB_DIR}}/node_modules
    silent: true
